name: Python Tests

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.0.0
    - name: Run tests
      id: run-tests
      run: >
        uv run pytest \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:coverage.xml \
          --cov=src \
          --log-level=DEBUG \
          --verbose tests
    - name: Coverage comment
      if: github.event_name == 'pull_request'
      uses: MishaKav/pytest-coverage-comment@v1
      with:
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.0.0
    - run: uv sync --only-dev
    - name: Ruff format
      run: uv run ruff format --check ./src
    - name: Ruff check
      run: uv run ruff check ./src

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.0.0
    - run: uv sync --only-dev
    - run: uv run mypy ./src

  deptry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v8.0.0
    - run: uv sync --only-dev
    - run: uv run deptry ./src